### ISSUE TITLE
Xamarin Shell

### ISSUE THREAD

**Issue by MaxiTalenti** [aimore/XamUI#2]
Hi, do you plan to pass XamFood to Xamarin Shell?

**Comment by aimore** [comment]
@MaxiTalenti yes I do, I need to dig into the Xamarin.Forms Shell Custom Renderers overrides to customise the bottombar I believe could be done on `CreateShellSectionRenderer` .
Can't say exactly when I am going to do this since I have another 2 UIs challenges on the pipeline but feel free to request a PR if you want to contribute or include any feature.

Cheers

**Comment by aimore** [comment]
Inactive
